// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteBancoParana.DAO;

#nullable disable

namespace TesteBancoParana.DAO.Migrations
{
    [DbContext(typeof(TesteBancoParanaContext))]
    partial class TesteBancoParanaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesteBancoParana.Model.Entities.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCliente"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TesteBancoParana.Model.Entities.Telefones", b =>
                {
                    b.Property<int>("idTelefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTelefone"));

                    b.Property<int>("ClienteidCliente")
                        .HasColumnType("int");

                    b.Property<int>("ddd")
                        .HasColumnType("int");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<int>("tipoTelefone")
                        .HasColumnType("int");

                    b.HasKey("idTelefone");

                    b.HasIndex("ClienteidCliente");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("TesteBancoParana.Model.Entities.Telefones", b =>
                {
                    b.HasOne("TesteBancoParana.Model.Entities.Cliente", null)
                        .WithMany("telefones")
                        .HasForeignKey("ClienteidCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TesteBancoParana.Model.Entities.Cliente", b =>
                {
                    b.Navigation("telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
